/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   info-icon-tooltip.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html} from 'lit-element';

/**
 * `etools-info-tooltip`
 * Tooltip element associated with form elements (or any other element), an icon is used to trigger tooltip open.
 */
declare class InfoIconTooltip extends LitElement {
  tooltipText: string|null|undefined;
  position: string|null|undefined;
  offset: number|null|undefined;

  connectedCallback(): void;
  showTooltip(): void;
  fixTooltipPosition(tooltip: any): void;
  hideTooltip(): void;
  close(): void;
}

declare global {

  interface HTMLElementTagNameMap {
    "info-icon-tooltip": InfoIconTooltip;
  }
}
